---
abstract: unknown
author:
  - 'William Travis Holton <heytrav@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.130880'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-Libravatar
no_index:
  directory:
    - t
    - inc
requires:
  Gravatar::URL: 0
  Libravatar::URL: 0
  Mojolicious: 0
  Test::Exception: 0
  Test::Routine: 0
version: 1.09
